apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      # containers:
      # - name: devops-app
      #   image: gauravsdevops/devops-app:latest
      containers:
      - name: devops-app
        image: gauravsdevops/devops-app:latest
        ports:
        - containerPort: 5000

        
